# Generated by Django 5.2.17 on 2026-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_username',
            field=models.CharField(blank=True, db_collation='uca1400_swedish_as_ci', max_length=50, null=True, unique=True, verbose_name='publikt användarnamn'),
        ),
    ]
