# Generated by Django 5.2.17 on 2026-09-12 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breedings', '0006_speciesreclassificationrequest'),
        ('taxonomy', '0011_species_cl_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='associationcompetitionlimit',
            name='unique_association_genus_limit_per_year',
        ),
        migrations.RemoveConstraint(
            model_name='associationcompetitionlimit',
            name='unique_association_group_limit_per_year',
        ),
        migrations.RemoveConstraint(
            model_name='speciesreclassificationrequest',
            name='unique_pending_reclassification_per_species',
        ),
        migrations.AddField(
            model_name='speciesreclassificationrequest',
            name='pending_species_key',
            field=models.GeneratedField(db_persist=False, expression=models.Case(models.When(status='pending', then=models.F('species')), default=models.Value(None), output_field=models.BigIntegerField()), null=True, output_field=models.BigIntegerField()),
        ),
        migrations.AddConstraint(
            model_name='associationcompetitionlimit',
            constraint=models.UniqueConstraint(fields=('effective_from_year', 'genus'), name='unique_association_genus_limit_per_year'),
        ),
        migrations.AddConstraint(
            model_name='associationcompetitionlimit',
            constraint=models.UniqueConstraint(fields=('effective_from_year', 'species_group'), name='unique_association_group_limit_per_year'),
        ),
        migrations.AddConstraint(
            model_name='speciesreclassificationrequest',
            constraint=models.UniqueConstraint(fields=('pending_species_key',), name='unique_pending_reclassification_per_species'),
        ),
    ]
