# Generated by Django 5.2.17 on 2026-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0011_species_cl_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='geography',
            name='unique_geography_name_ci',
        ),
        migrations.AlterField(
            model_name='commonnamespeciessynonym',
            name='common_name',
            field=models.CharField(db_collation='uca1400_swedish_as_ci', max_length=200, verbose_name='populärnamn'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='scientific_name',
            field=models.CharField(db_collation='uca1400_swedish_as_ci', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='geography',
            name='name',
            field=models.CharField(db_collation='uca1400_swedish_as_ci', max_length=100, unique=True, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='scientificspeciessynonym',
            name='scientific_name',
            field=models.CharField(db_collation='uca1400_swedish_as_ci', max_length=200, verbose_name='vetenskapligt namn'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(db_collation='uca1400_swedish_as_ci', max_length=100, verbose_name='artnamn'),
        ),
        migrations.AlterField(
            model_name='speciesgroup',
            name='name',
            field=models.CharField(db_collation='uca1400_swedish_as_ci', max_length=100, unique=True, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='specieslink',
            name='url',
            field=models.URLField(db_collation='utf8mb4_bin', max_length=500, verbose_name='URL'),
        ),
    ]
