# Generated by Django 5.2.17 on 2026-09-12 16:55

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0010_requirementtexttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userachievement',
            name='unique_lifetime_user_achievement',
        ),
        migrations.RemoveConstraint(
            model_name='userachievement',
            name='unique_yearly_user_achievement',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement_period_key',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.functions.comparison.Coalesce('calendar_year', models.Value(-1)), output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'level', 'achievement_period_key'), name='unique_user_achievement_period'),
        ),
    ]
