# Generated by Django 5.2.17 on 2026-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0011_remove_userachievement_unique_lifetime_user_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(db_collation='uca1400_swedish_as_ci', max_length=100, unique=True, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='achievementlevel',
            name='name',
            field=models.CharField(db_collation='uca1400_swedish_as_ci', max_length=15, verbose_name='nivånamn'),
        ),
        migrations.AlterField(
            model_name='requirementtexttemplate',
            name='kind',
            field=models.CharField(choices=[('points', 'Poäng'), ('breeding_count', 'Antal odlingar'), ('species_count', 'Antal arter')], db_collation='uca1400_swedish_as_ci', max_length=20, unique=True, verbose_name='kravtyp'),
        ),
    ]
